version: "3.2"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: PokemonAPI
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    container_name: api
    image: api
    restart: always
    command : bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  mysql_data:
