version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    env_file:
      - ./mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql:rw
  redis:
    container_name: redis
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data:rw
  api:
    container_name: api
    image: api
    build: api
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - api_static:/opt/app/static:rw
    depends_on:
      - mysql
      - redis
  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_data:/var/www/certbot/:ro
      - ssl_certs:/etc/letsencrypt/:ro
      - api_static:/opt/api/static:ro
    depends_on:
      - api
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/cli.ini:/etc/letsencrypt/cli.ini:ro
      - certbot_data:/var/www/certbot/:rw
      - ssl_certs:/etc/letsencrypt/:rw
    depends_on:
      - nginx
volumes:
  mysql_data:
  redis_data:
  api_static:
  certbot_data:
  ssl_certs:
