version: "3.2"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: PokemonAPI
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:5
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  api:
    container_name: api
    image: api
    build: api
    restart: always
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    volumes:
      - api_static:/app/static
    depends_on:
      - mysql
      - redis
  nginx:
    container_name: nginx
    image: nginx
    build: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - api_static:/app/static
    depends_on:
      - api

volumes:
  mysql_data:
  redis_data:
  api_static:
