# Generated by Django 5.0.3 on 2024-03-14 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30), django.core.validators.RegexValidator("^[A-Z][A-Za-z0-9% \\-'\\.\\(\\)]+$"), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
