# Generated by Django 5.0.6 on 2024-07-16 18:35

import django.core.validators
import django_choices_field.fields
import pokemon.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type1',
            field=django_choices_field.fields.TextChoicesField(choices=[('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water')], choices_enum=pokemon.models.TypeCategory, max_length=10, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^[A-Z][a-z]{2,9}$'), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type2',
            field=django_choices_field.fields.TextChoicesField(choices=[('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water')], choices_enum=pokemon.models.TypeCategory, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^[A-Z][a-z]{2,9}$'), django.core.validators.ProhibitNullCharactersValidator()]),
        ),
    ]
