# Generated by Django 5.1.7 on 2025-03-18 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_type1_alter_pokemon_type2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='generation',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
